# Generated by Django 5.1 on 2024-08-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="notes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("year", models.IntegerField(max_length=2)),
                ("subject", models.CharField(max_length=100)),
                ("url", models.FileField(upload_to="satic/notes/")),
            ],
        ),
    ]
