# Generated by Django 5.1 on 2024-08-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notes",
            name="year",
            field=models.IntegerField(),
        ),
    ]
