# Generated by Django 5.1 on 2024-08-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_notes_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("image", models.ImageField(upload_to="static/photos")),
                ("testi", models.TextField()),
                ("git", models.URLField()),
                ("linkdin", models.URLField()),
            ],
        ),
    ]
