# Generated by Django 4.2.15 on 2024-08-15 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_testimonial_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="testimonial", old_name="title", new_name="name",
        ),
    ]
