# Generated by Django 5.1 on 2024-08-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_events_roadmaps_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmaps',
            name='url',
            field=models.FileField(upload_to='satic/roadmaps/'),
        ),
    ]
