# Generated by Django 5.1 on 2024-08-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_alter_roadmaps_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
