# Generated by Django 5.1 on 2024-08-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_roadmaps_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='docs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.FileField(upload_to='satic/docs')),
            ],
        ),
    ]
