# Generated by Django 5.1 on 2024-08-17 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_docs"),
        ("user", "0010_notes_unit"),
    ]

    operations = []
